from django.urls import path
from .views import *

urlpatterns = [
    path("user", appview.as_view()),
    path("check", checkEmail.as_view()),
    path("send", sendMessage.as_view()),
    path("add", CreateUser.as_view()),
    path("logval", LoginChecker.as_view()),
    path("change", ChangePassword.as_view()),
    path("addusercookie", SetUserCookies.as_view()),
    path("addguestcookie", SetGuestCookies.as_view()),
    path("checkcookie", CheckCookies.as_view()),
    path('getuserid',getuserid.as_view()),
    path('getdetail',getdetail.as_view()),
    path('getalllike',getalllike.as_view()),
    path("addguest", CreateGuest.as_view()),
    path("getiduser", getuserbyid.as_view()),
    path("getcookieguest", getguestbyid.as_view()),
    path("addnewsave", savepuzzle.as_view()),
    path("addnewsubmit", newpuzzle.as_view()),
    path('changeusername',changeusername.as_view()),
    path('changeuserimg',changeuserimg.as_view()),
    path("getinittop", getinittop.as_view()),
    path("getinituser", getinituser.as_view()),
    path('getmoreup',getmoreup.as_view()),
    path('getmoredown',getmoredown.as_view()),
    path('getpuzbyname',getpuzbyname.as_view()),
    path('savelocalpuz',savelocalpuz.as_view()),
    path('donelocalpuz',puzzlesolved.as_view()),
    path('getuserfilpuzzlenewpage',getuserfilpuzzlenewpage.as_view()),
    path('like',like.as_view()),
    path('getvisit',getvisit.as_view()),
    path('visitnewcontent',visitnewcontent.as_view()),
    path('getsavepuz',getsavepuz.as_view()),
    path('logout',logout.as_view()),
]